<?php

/**
 * @file
 * Contains smmg_ckeditor_plugins.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smmg_ckeditor_plugins_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smmg_ckeditor_plugins module.
    case 'help.page.smmg_ckeditor_plugins':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SMMG CKEditor Plugins') . '</p>';
      return $output;

    default:
  }
}

function smmg_ckeditor_plugins_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'smmg_ckeditor_plugins/cke_smmg';
}
